# Generated by Django 5.1.1 on 2024-10-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_name', models.CharField(max_length=50)),
                ('Middle_name', models.CharField(max_length=50)),
                ('First_name', models.CharField(max_length=50)),
                ('Id_number', models.IntegerField()),
                ('Phone_number', models.IntegerField()),
                ('patient_number', models.IntegerField()),
                ('Admission_date', models.DateTimeField(auto_now_add=True)),
                ('Discharge', models.BooleanField(default=False)),
            ],
        ),
    ]
